###
GET http://localhost:3000/api/todos
###
GET http://localhost:3000/api/todos/8
###

###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Learn Node.js and Express",
  "description": "Study the basics of Node.js and Express",
  "is_completed": null,
  "user_id": 1,
  "category_id": 6,
  "due_date": "2024-12-31"
}

###
DELETE http://localhost:3000/api/todos/1

###
PUT http://localhost:3000/api/todos/8
Content-Type: application/json

{
  "title": "memakai dasi"
}