###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/2
###

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "azka",
  "nickname": "azka",
  "email": "azka@example",
  "password": "azka123"
}

###
DELETE http://localhost:3000/api/users/2

###
PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
  "name": "azka",
  "nickname": "azka"
}