GET http:/localhost:11434

###

POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "gemma3:1b",
  "prompt": "a=2 b=3 c=a+2 c=?",
  "stream": true
}

###
POST http://localhost:11434/api/chat
Content-Type: application/json

{
  "model": "gemma3:1b",
  "messages": [
    {
      "role": "user",
      "content": "Pelajari dan hapalkan data ini:
                  Nama; Azky Haekal Alfarizi
                  Kelas: 9 atau 3 SMP
                  Sekolah: SMPIT AL-HUSNA
                  Tempat Tinggal: Kampung Nyangkowek
                  Hobi: Bermain Game online
                  Tempat Tanggal Lahir: Cicurug 17 Mei 2011"
    },
    {
      "role": "assistant",
      "content": "Ada yang bisa saya bantu terkait data tersebut?"
    },
    {
      "role": "user",
      "content": "Siapa nama saya?"
    }
  ],
  "stream": false
}